// AUTO-GENERATED by scripts/build-docs-index.ts. Do not edit by hand.
// Re-run `pnpm run build:docs` to regenerate.

export type MethodEntry = {
	kind: "method";
	name: string;
	qualified: string;
	description: string;
	params: unknown;
	exampleCall: string;
};

export type ProseEntry = {
	kind: "prose";
	id: string;
	title: string;
	content: string;
};

export type IndexEntry = MethodEntry | ProseEntry;

export const ENTRIES: IndexEntry[] = [
	{
		kind: "method",
		name: "debank_get_supported_chain_list",
		qualified: "debank.chain.getSupportedChainList",
		description:
			"Retrieve a comprehensive list of all blockchain chains supported by the DeBank API. Returns information about each chain including their IDs, names, logo URLs, native token IDs, wrapped token IDs, and pre-execution support status. Use this to discover available chains before calling other chain-specific endpoints.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {},
			additionalProperties: false,
		},
		exampleCall: "await debank.chain.getSupportedChainList()",
	},
	{
		kind: "method",
		name: "debank_get_chain",
		qualified: "debank.chain.getChain",
		description:
			"Retrieve detailed information about a specific blockchain chain supported by DeBank. Returns chain details including ID, name, logo URL, native token ID, wrapped token ID, and whether it supports pre-execution of transactions.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				id: {
					description:
						"Chain ID (e.g. 'eth', 'bsc', 'matic', 'arb', 'op', 'base', 'avax').",
					type: "string",
				},
			},
			required: ["id"],
			additionalProperties: false,
		},
		exampleCall: "await debank.chain.getChain({id: 'eth'})",
	},
	{
		kind: "method",
		name: "debank_get_all_protocols_of_supported_chains",
		qualified: "debank.protocol.getAllProtocolsOfSupportedChains",
		description:
			"Retrieve a list of all DeFi protocols across specified or all supported blockchain chains. Returns essential information about each protocol including ID, chain ID, name, logo URL, site URL, portfolio support status, and TVL. Returns top 20 protocols by default. Filter by specific chains using chain_ids parameter.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				chain_ids: {
					description:
						"Comma-separated chain IDs (e.g. 'eth,bsc,matic'). If omitted, returns protocols across all supported chains.",
					type: "string",
				},
			},
			additionalProperties: false,
		},
		exampleCall:
			"await debank.protocol.getAllProtocolsOfSupportedChains({chain_ids: 'eth,bsc'})",
	},
	{
		kind: "method",
		name: "debank_get_protocol_list",
		qualified: "debank.protocol.getProtocolList",
		description:
			"Retrieve all DeFi protocols available on a specific blockchain. Returns each protocol's ID, chain, name, logo URL, site URL, portfolio support status, and TVL. Use when you want the protocol catalog for a single chain rather than the cross-chain list.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				chain_id: {
					description:
						"Chain ID (e.g. 'eth', 'bsc', 'matic', 'arb', 'op', 'base', 'avax').",
					type: "string",
				},
			},
			required: ["chain_id"],
			additionalProperties: false,
		},
		exampleCall: "await debank.protocol.getProtocolList({chain_id: 'eth'})",
	},
	{
		kind: "method",
		name: "debank_get_app_protocol_list",
		qualified: "debank.protocol.getAppProtocolList",
		description:
			"Retrieve the catalog of supported app-protocols (cross-chain dApps that wrap multiple underlying protocols). Returns id, name, site_url, logo_url, and portfolio support status for each. No parameters required.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {},
			additionalProperties: false,
		},
		exampleCall: "await debank.protocol.getAppProtocolList()",
	},
	{
		kind: "method",
		name: "debank_get_protocol_information",
		qualified: "debank.protocol.getProtocolInformation",
		description:
			"Fetch detailed information about a specific DeFi protocol. Returns protocol details including ID, associated chain, name, logo URL, site URL, portfolio support status, and total value locked (TVL). Useful for analyzing individual protocols across different chains.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				id: {
					description:
						"The unique identifier of the protocol (e.g., 'bsc_pancakeswap' for PancakeSwap on BSC, 'uniswap', 'aave', 'curve'). Use debank_get_all_protocols_of_supported_chains to discover protocol IDs.",
					type: "string",
				},
			},
			required: ["id"],
			additionalProperties: false,
		},
		exampleCall:
			"await debank.protocol.getProtocolInformation({id: 'uniswap'})",
	},
	{
		kind: "method",
		name: "debank_get_top_holders_of_protocol",
		qualified: "debank.protocol.getTopHoldersOfProtocol",
		description:
			"Retrieve a list of top holders within a specified DeFi protocol, ranked by their holdings. Provides insights into the distribution and concentration of holdings among participants. Supports pagination for large result sets.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				id: {
					description:
						"The unique identifier of the protocol (e.g., 'uniswap', 'aave', 'compound'). Use debank_get_all_protocols_of_supported_chains to find protocol IDs.",
					type: "string",
				},
				start: {
					description:
						"Pagination offset to specify where to start in the list. Default is 0, maximum is 1000.",
					type: "integer",
					minimum: 0,
					maximum: 1000,
				},
				limit: {
					description:
						"Maximum number of top holders to retrieve. Default and maximum is 100.",
					type: "integer",
					exclusiveMinimum: 0,
					maximum: 100,
				},
			},
			required: ["id"],
			additionalProperties: false,
		},
		exampleCall:
			"await debank.protocol.getTopHoldersOfProtocol({id: 'uniswap', limit: 10})",
	},
	{
		kind: "method",
		name: "debank_get_pool_information",
		qualified: "debank.protocol.getPoolInformation",
		description:
			"Retrieve detailed information about a specific liquidity pool. Returns pool details including ID, chain, protocol ID, contract IDs, name, USD value of deposited assets, total user count, and count of valuable users (>$100 USD value). Essential for analyzing specific pools for investment or research.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				id: {
					description:
						"The unique identifier of the pool (typically a contract address, e.g., '0x00000000219ab540356cbb839cbe05303d7705fa').",
					type: "string",
				},
				chain_id: {
					description:
						"Chain ID (e.g. 'eth', 'bsc', 'matic', 'arb', 'op', 'base', 'avax').",
					type: "string",
				},
			},
			required: ["id", "chain_id"],
			additionalProperties: false,
		},
		exampleCall:
			"await debank.protocol.getPoolInformation({id: '0x...', chain_id: 'eth'})",
	},
	{
		kind: "method",
		name: "debank_get_token_information",
		qualified: "debank.token.getTokenInformation",
		description:
			"Fetch comprehensive details about a specific token on a blockchain. Returns token information including contract address, chain, name, symbol, decimals, logo URL, associated protocol ID, USD price, verification status, and deployment timestamp. Essential for token analysis and display.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				chain_id: {
					description:
						"Chain ID (e.g. 'eth', 'bsc', 'matic', 'arb', 'op', 'base', 'avax').",
					type: "string",
				},
				id: {
					description:
						"Token contract address or native token ID (e.g., '0xdac17f958d2ee523a2206206994597c13d831ec7' for USDT). Use debank.resolveWrappedToken() in execute() to resolve wrapped token keywords to addresses before passing here.",
					type: "string",
				},
			},
			required: ["chain_id", "id"],
			additionalProperties: false,
		},
		exampleCall:
			"await debank.token.getTokenInformation({chain_id: 'eth', id: '0xdac17f958d2ee523a2206206994597c13d831ec7'})",
	},
	{
		kind: "method",
		name: "debank_get_list_token_information",
		qualified: "debank.token.getListTokenInformation",
		description:
			"Retrieve detailed information for multiple tokens at once on a specific chain. Returns an array of token objects with comprehensive details. Useful for bulk token data retrieval, with support for up to 100 token addresses per request.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				chain_id: {
					description:
						"Chain ID (e.g. 'eth', 'bsc', 'matic', 'arb', 'op', 'base', 'avax').",
					type: "string",
				},
				ids: {
					description:
						"Comma-separated list of token addresses (up to 100). Example: '0xdac17f958d2ee523a2206206994597c13d831ec7,0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48'",
					type: "string",
				},
			},
			required: ["chain_id", "ids"],
			additionalProperties: false,
		},
		exampleCall:
			"await debank.token.getListTokenInformation({chain_id: 'eth', ids: '0xdac17f958d2ee523a2206206994597c13d831ec7'})",
	},
	{
		kind: "method",
		name: "debank_get_top_holders_of_token",
		qualified: "debank.token.getTopHoldersOfToken",
		description:
			"Fetch the top holders of a specified token, showing the largest token holders ranked by their holdings. Supports both contract addresses and native token IDs. Useful for analyzing token distribution and ownership concentration. Supports pagination for detailed analysis.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				id: {
					description:
						"Token contract address or native token ID (e.g., '0xdac17f958d2ee523a2206206994597c13d831ec7'). Use debank.resolveWrappedToken() in execute() to resolve wrapped token keywords to addresses before passing here.",
					type: "string",
				},
				chain_id: {
					description:
						"Chain ID (e.g. 'eth', 'bsc', 'matic', 'arb', 'op', 'base', 'avax').",
					type: "string",
				},
				start: {
					description: "Pagination offset. Default is 0, maximum is 10000.",
					type: "integer",
					minimum: 0,
					maximum: 10000,
				},
				limit: {
					description: "Maximum number of holders to return. Default is 100.",
					type: "integer",
					exclusiveMinimum: 0,
					maximum: 100,
				},
			},
			required: ["id", "chain_id"],
			additionalProperties: false,
		},
		exampleCall:
			"await debank.token.getTopHoldersOfToken({id: '0xdac17f958d2ee523a2206206994597c13d831ec7', chain_id: 'eth', limit: 10})",
	},
	{
		kind: "method",
		name: "debank_get_token_history_price",
		qualified: "debank.token.getTokenHistoryPrice",
		description:
			"Retrieve the historical price of a specified token for a given date. Essential for financial analysis, historical comparison, and tracking price movements over time. Returns price data for the UTC time zone on the specified date.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				id: {
					description:
						"Token contract address or native token ID (e.g., '0xdac17f958d2ee523a2206206994597c13d831ec7'). Use debank.resolveWrappedToken() in execute() to resolve wrapped token keywords to addresses before passing here.",
					type: "string",
				},
				chain_id: {
					description:
						"Chain ID (e.g. 'eth', 'bsc', 'matic', 'arb', 'op', 'base', 'avax').",
					type: "string",
				},
				date_at: {
					description:
						"The date for historical price data in UTC time zone. Format: YYYY-MM-DD (e.g., '2023-05-18').",
					type: "string",
				},
			},
			required: ["id", "chain_id", "date_at"],
			additionalProperties: false,
		},
		exampleCall:
			"await debank.token.getTokenHistoryPrice({id: '0xdac17f958d2ee523a2206206994597c13d831ec7', chain_id: 'eth', date_at: '2023-05-18'})",
	},
	{
		kind: "method",
		name: "debank_get_user_used_chain_list",
		qualified: "debank.user.getUserUsedChainList",
		description:
			"Retrieve a list of blockchain chains that a specific user has interacted with. Returns details about each chain including ID, name, logo URL, native token ID, wrapped token ID, and the birth time of the user's address on each chain.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				id: {
					description: "The user's wallet address.",
					type: "string",
				},
			},
			required: ["id"],
			additionalProperties: false,
		},
		exampleCall: "await debank.user.getUserUsedChainList({id: '0x...'})",
	},
	{
		kind: "method",
		name: "debank_get_user_chain_balance",
		qualified: "debank.user.getUserChainBalance",
		description:
			"Fetch the current balance of a user's account on a specified blockchain chain. Returns the balance in USD value, providing a snapshot of the user's holdings on that chain.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				chain_id: {
					description:
						"Chain ID (e.g. 'eth', 'bsc', 'matic', 'arb', 'op', 'base', 'avax').",
					type: "string",
				},
				id: {
					description: "The user's wallet address.",
					type: "string",
				},
			},
			required: ["chain_id", "id"],
			additionalProperties: false,
		},
		exampleCall:
			"await debank.user.getUserChainBalance({id: '0x...', chain_id: 'eth'})",
	},
	{
		kind: "method",
		name: "debank_get_user_protocol",
		qualified: "debank.user.getUserProtocol",
		description:
			"Get detailed information about a user's positions within a specified DeFi protocol. Returns protocol details and the user's portfolio items including assets, debts, and rewards in that protocol.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				protocol_id: {
					description:
						"The protocol ID (e.g., 'bsc_pancakeswap', 'uniswap', 'aave')Use debank_get_all_protocols_of_supported_chains to discover protocol IDs..",
					type: "string",
				},
				id: {
					description: "The user's wallet address.",
					type: "string",
				},
			},
			required: ["protocol_id", "id"],
			additionalProperties: false,
		},
		exampleCall:
			"await debank.user.getUserProtocol({id: '0x...', protocol_id: 'uniswap'})",
	},
	{
		kind: "method",
		name: "debank_get_user_complex_protocol_list",
		qualified: "debank.user.getUserComplexProtocolList",
		description:
			"Retrieve detailed portfolios of a user on a specific chain across multiple protocols. Returns comprehensive information about the user's engagements including protocol details and portfolio items with assets, debts, and positions.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				chain_id: {
					description:
						"Chain ID (e.g. 'eth', 'bsc', 'matic', 'arb', 'op', 'base', 'avax').",
					type: "string",
				},
				id: {
					description: "The user's wallet address.",
					type: "string",
				},
			},
			required: ["chain_id", "id"],
			additionalProperties: false,
		},
		exampleCall:
			"await debank.user.getUserComplexProtocolList({id: '0x...', chain_id: 'eth'})",
	},
	{
		kind: "method",
		name: "debank_get_user_all_complex_protocol_list",
		qualified: "debank.user.getUserAllComplexProtocolList",
		description:
			"Retrieve a user's detailed portfolios across all supported chains within multiple protocols. Provides a comprehensive overview of investments and positions across the entire DeFi ecosystem. Can be filtered by specific chains.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				id: {
					description: "The user's wallet address.",
					type: "string",
				},
				chain_ids: {
					description:
						"Comma-separated chain IDs (e.g. 'eth,bsc,matic'). If omitted, includes all supported chains.",
					type: "string",
				},
			},
			required: ["id"],
			additionalProperties: false,
		},
		exampleCall:
			"await debank.user.getUserAllComplexProtocolList({id: '0x...'})",
	},
	{
		kind: "method",
		name: "debank_get_user_all_simple_protocol_list",
		qualified: "debank.user.getUserAllSimpleProtocolList",
		description:
			"Fetch a user's balances in protocols across all supported chains. Returns simplified protocol information including TVL and basic details. Useful for getting a quick overview of a user's protocol engagements.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				id: {
					description: "The user's wallet address.",
					type: "string",
				},
				chain_ids: {
					description:
						"Comma-separated chain IDs (e.g. 'eth,bsc,matic'). If omitted, includes all supported chains.",
					type: "string",
				},
			},
			required: ["id"],
			additionalProperties: false,
		},
		exampleCall:
			"await debank.user.getUserAllSimpleProtocolList({id: '0x...'})",
	},
	{
		kind: "method",
		name: "debank_get_user_simple_protocol_list",
		qualified: "debank.user.getUserSimpleProtocolList",
		description:
			"Retrieve a user's protocol balances on a single chain. Returns each protocol's aggregate position (TVL, net/asset/debt USD value) without detailed per-position breakdowns — cheaper than the complex variant when you only need totals. Use the all-chains variant when you need cross-chain coverage.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				id: {
					description: "The user's wallet address.",
					type: "string",
				},
				chain_id: {
					description:
						"Chain ID (e.g. 'eth', 'bsc', 'matic', 'arb', 'op', 'base', 'avax').",
					type: "string",
				},
			},
			required: ["id", "chain_id"],
			additionalProperties: false,
		},
		exampleCall:
			"await debank.user.getUserSimpleProtocolList({id: '0x...', chain_id: 'eth'})",
	},
	{
		kind: "method",
		name: "debank_get_user_complex_app_list",
		qualified: "debank.user.getUserComplexAppList",
		description:
			"Retrieve a user's detailed positions across all app-protocols (cross-chain dApps that wrap multiple underlying protocols). Returns full portfolio_item_list breakdowns for each app. Use when you need app-level (not chain-level) views of DeFi exposure.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				id: {
					description: "The user's wallet address.",
					type: "string",
				},
			},
			required: ["id"],
			additionalProperties: false,
		},
		exampleCall: "await debank.user.getUserComplexAppList({id: '0x...'})",
	},
	{
		kind: "method",
		name: "debank_get_user_token_balance",
		qualified: "debank.user.getUserTokenBalance",
		description:
			"Retrieve a user's balance for a specific token. Returns detailed token information including name, symbol, decimals, USD price, and the user's balance amount.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				chain_id: {
					description:
						"Chain ID (e.g. 'eth', 'bsc', 'matic', 'arb', 'op', 'base', 'avax').",
					type: "string",
				},
				id: {
					description: "The user's wallet address.",
					type: "string",
				},
				token_id: {
					description:
						"Token contract address or native token ID (e.g., '0xdac17f958d2ee523a2206206994597c13d831ec7'). Use debank.resolveWrappedToken() in execute() to resolve wrapped token keywords to addresses before passing here.",
					type: "string",
				},
			},
			required: ["chain_id", "id", "token_id"],
			additionalProperties: false,
		},
		exampleCall:
			"await debank.user.getUserTokenBalance({id: '0x...', chain_id: 'eth', token_id: '0xdac17f958d2ee523a2206206994597c13d831ec7'})",
	},
	{
		kind: "method",
		name: "debank_get_user_token_list",
		qualified: "debank.user.getUserTokenList",
		description:
			"Retrieve a list of tokens held by a user on a specific chain. Returns token details including symbol, decimals, USD price, and balance amounts. Can filter for core/verified tokens or include all tokens.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				id: {
					description: "The user's wallet address.",
					type: "string",
				},
				chain_id: {
					description:
						"Chain ID (e.g. 'eth', 'bsc', 'matic', 'arb', 'op', 'base', 'avax').",
					type: "string",
				},
				is_all: {
					description:
						"If true, returns all tokens including non-core tokens. Default is true.",
					type: "boolean",
				},
			},
			required: ["id", "chain_id"],
			additionalProperties: false,
		},
		exampleCall:
			"await debank.user.getUserTokenList({id: '0x...', chain_id: 'eth'})",
	},
	{
		kind: "method",
		name: "debank_get_user_tokens_across_chains",
		qualified: "debank.user.getUserTokensAcrossChains",
		description:
			"Retrieve a user's token balances across every chain that holds value. Host-side aggregate: discovers active chains via getUserTotalBalance, filters to those with usd_value >= min_usd_value (default 1), then fans out per-chain token_list calls in parallel. Replaces DeBank's /user/all_token_list endpoint, which cannot reliably serve active wallets within the 5 s per-call timeout. Returns a flat array of token balances; each token carries its `chain` field for grouping.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				id: {
					description: "The user's wallet address.",
					type: "string",
				},
				min_usd_value: {
					description:
						"Minimum per-chain USD value required for that chain to be queried. Default 1 — skips the long tail of dust chains. Pass 0 to query every chain the wallet has touched.",
					type: "number",
				},
				is_all: {
					description:
						"If true, includes non-core tokens in each per-chain response.",
					type: "boolean",
				},
			},
			required: ["id"],
			additionalProperties: false,
		},
		exampleCall:
			"await debank.user.getUserTokensAcrossChains({id: '0x...', min_usd_value: 1})",
	},
	{
		kind: "method",
		name: "debank_get_user_nft_list",
		qualified: "debank.user.getUserNftList",
		description:
			"Fetch a list of NFTs owned by a user on a specific chain. Returns NFT details including contract ID, name, description, content type, and attributes. Can filter for verified collections only.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				id: {
					description: "The user's wallet address.",
					type: "string",
				},
				chain_id: {
					description:
						"Chain ID (e.g. 'eth', 'bsc', 'matic', 'arb', 'op', 'base', 'avax').",
					type: "string",
				},
				is_all: {
					description:
						"If false, only returns NFTs from verified collections. Default is true.",
					type: "boolean",
				},
			},
			required: ["id", "chain_id"],
			additionalProperties: false,
		},
		exampleCall:
			"await debank.user.getUserNftList({id: '0x...', chain_id: 'eth'})",
	},
	{
		kind: "method",
		name: "debank_get_user_all_nft_list",
		qualified: "debank.user.getUserAllNftList",
		description:
			"Retrieve a user's NFT holdings across all supported chains. Provides an aggregate list of NFTs held by the user with details including contract ID, name, and content type. Can be filtered by specific chains.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				id: {
					description: "The user's wallet address.",
					type: "string",
				},
				is_all: {
					description: "If true, includes all NFTs. Default is true.",
					type: "boolean",
				},
				chain_ids: {
					description:
						"Comma-separated chain IDs (e.g. 'eth,bsc,matic'). If omitted, includes all supported chains.",
					type: "string",
				},
			},
			required: ["id"],
			additionalProperties: false,
		},
		exampleCall: "await debank.user.getUserAllNftList({id: '0x...'})",
	},
	{
		kind: "method",
		name: "debank_get_user_history_list",
		qualified: "debank.user.getUserHistoryList",
		description:
			"Fetch a user's transaction history on a specified chain. Returns a list of past transactions with details including transaction type, tokens involved, values, and timestamps. Supports pagination.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				id: {
					description: "The user's wallet address.",
					type: "string",
				},
				chain_id: {
					description:
						"Chain ID (e.g. 'eth', 'bsc', 'matic', 'arb', 'op', 'base', 'avax').",
					type: "string",
				},
				start_time: {
					description:
						"Optional timestamp to return history earlier than this time (Unix timestamp).",
					type: "integer",
					minimum: -9007199254740991,
					maximum: 9007199254740991,
				},
				page_count: {
					description: "Number of entries to return. Maximum is 20.",
					type: "integer",
					exclusiveMinimum: 0,
					maximum: 20,
				},
			},
			required: ["id", "chain_id"],
			additionalProperties: false,
		},
		exampleCall:
			"await debank.user.getUserHistoryList({id: '0x...', chain_id: 'eth'})",
	},
	{
		kind: "method",
		name: "debank_get_user_all_history_list",
		qualified: "debank.user.getUserAllHistoryList",
		description:
			"Retrieve a user's transaction history across all supported chains. Provides a comprehensive overview of DeFi activities across the entire blockchain ecosystem. Supports pagination.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				id: {
					description: "The user's wallet address.",
					type: "string",
				},
				start_time: {
					description:
						"Optional timestamp to return history earlier than this time.",
					type: "integer",
					minimum: -9007199254740991,
					maximum: 9007199254740991,
				},
				page_count: {
					description: "Number of entries to return. Maximum is 20.",
					type: "integer",
					exclusiveMinimum: 0,
					maximum: 20,
				},
			},
			required: ["id"],
			additionalProperties: false,
		},
		exampleCall: "await debank.user.getUserAllHistoryList({id: '0x...'})",
	},
	{
		kind: "method",
		name: "debank_get_user_token_authorized_list",
		qualified: "debank.user.getUserTokenAuthorizedList",
		description:
			"Fetch a list of tokens for which a user has granted spending approvals on a specified chain. Returns details about each approval including amount, spender address, and associated protocol information. Useful for security audits.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				id: {
					description: "The user's wallet address.",
					type: "string",
				},
				chain_id: {
					description:
						"Chain ID (e.g. 'eth', 'bsc', 'matic', 'arb', 'op', 'base', 'avax').",
					type: "string",
				},
			},
			required: ["id", "chain_id"],
			additionalProperties: false,
		},
		exampleCall:
			"await debank.user.getUserTokenAuthorizedList({id: '0x...', chain_id: 'eth'})",
	},
	{
		kind: "method",
		name: "debank_get_user_nft_authorized_list",
		qualified: "debank.user.getUserNftAuthorizedList",
		description:
			"Retrieve a list of NFTs for which a user has given spending permissions on a specified chain. Returns details including contract IDs, names, symbols, spender addresses, and approved amounts for ERC1155 tokens. Important for security reviews.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				id: {
					description: "The user's wallet address.",
					type: "string",
				},
				chain_id: {
					description:
						"Chain ID (e.g. 'eth', 'bsc', 'matic', 'arb', 'op', 'base', 'avax').",
					type: "string",
				},
			},
			required: ["id", "chain_id"],
			additionalProperties: false,
		},
		exampleCall:
			"await debank.user.getUserNftAuthorizedList({id: '0x...', chain_id: 'eth'})",
	},
	{
		kind: "method",
		name: "debank_get_user_total_balance",
		qualified: "debank.user.getUserTotalBalance",
		description:
			"Retrieve a user's total net assets across all supported chains. Calculates and returns the total USD value of assets including both tokens and protocol positions. Provides a complete snapshot of the user's DeFi portfolio.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				id: {
					description: "The user's wallet address.",
					type: "string",
				},
			},
			required: ["id"],
			additionalProperties: false,
		},
		exampleCall: "await debank.user.getUserTotalBalance({id: '0x...'})",
	},
	{
		kind: "method",
		name: "debank_get_user_chain_net_curve",
		qualified: "debank.user.getUserChainNetCurve",
		description:
			"Retrieve a user's 24-hour net asset value curve on a single chain. Shows the changes in total USD value of assets over the last 24 hours, providing insights into portfolio fluctuations on that specific chain.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				id: {
					description: "The user's wallet address.",
					type: "string",
				},
				chain_id: {
					description:
						"Chain ID (e.g. 'eth', 'bsc', 'matic', 'arb', 'op', 'base', 'avax').",
					type: "string",
				},
			},
			required: ["id", "chain_id"],
			additionalProperties: false,
		},
		exampleCall:
			"await debank.user.getUserChainNetCurve({id: '0x...', chain_id: 'eth'})",
	},
	{
		kind: "method",
		name: "debank_get_user_total_net_curve",
		qualified: "debank.user.getUserTotalNetCurve",
		description:
			"Retrieve a user's 24-hour net asset value curve across all chains. Provides a comprehensive view of total USD value changes over the last 24 hours, helping track overall portfolio performance. Can be filtered by specific chains.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				id: {
					description: "The user's wallet address.",
					type: "string",
				},
				chain_ids: {
					description:
						"Comma-separated chain IDs (e.g. 'eth,bsc,matic'). If omitted, includes all supported chains.",
					type: "string",
				},
			},
			required: ["id"],
			additionalProperties: false,
		},
		exampleCall: "await debank.user.getUserTotalNetCurve({id: '0x...'})",
	},
	{
		kind: "method",
		name: "debank_get_gas_prices",
		qualified: "debank.chain.getGasPrices",
		description:
			"Fetch current gas prices for different transaction speed levels on a specified chain. Returns prices for slow, normal, and fast transaction speeds with estimated confirmation times. Crucial for transaction cost estimation.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				chain_id: {
					description:
						"Chain ID (e.g. 'eth', 'bsc', 'matic', 'arb', 'op', 'base', 'avax').",
					type: "string",
				},
			},
			required: ["chain_id"],
			additionalProperties: false,
		},
		exampleCall: "await debank.chain.getGasPrices({chain_id: 'eth'})",
	},
	{
		kind: "method",
		name: "debank_pre_exec_transaction",
		qualified: "debank.transaction.preExecTransaction",
		description:
			"Simulate the execution of a transaction or sequence of transactions before submitting them on-chain. Returns detailed information about balance changes, gas estimates, and success status. Useful for DEX swaps requiring token approvals or complex transaction sequences.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				tx: {
					description:
						"The main transaction object as a JSON string. Must include fields like from, to, data, value, etc.",
					type: "string",
				},
				pending_tx_list: {
					description:
						"Optional JSON string array of transactions to execute before the main transaction (e.g., approval transactions).",
					type: "string",
				},
			},
			required: ["tx"],
			additionalProperties: false,
		},
		exampleCall:
			'await debank.transaction.preExecTransaction({tx: \'{"from":"0x...","to":"0x...","data":"0x...","value":"0x0"}\'})',
	},
	{
		kind: "method",
		name: "debank_explain_transaction",
		qualified: "debank.transaction.explainTransaction",
		description:
			"Decode and explain a given transaction in human-readable terms. Returns details about function calls, parameters, and actions derived from the transaction data. Supports complex transactions across multiple protocols.",
		params: {
			$schema: "https://json-schema.org/draft/2020-12/schema",
			type: "object",
			properties: {
				tx: {
					description:
						"The transaction object as a JSON string to be explained. Must include transaction data field.",
					type: "string",
				},
			},
			required: ["tx"],
			additionalProperties: false,
		},
		exampleCall:
			'await debank.transaction.explainTransaction({tx: \'{"from":"0x...","to":"0x...","data":"0x..."}\'})',
	},
	{
		kind: "prose",
		id: "cookbook:01-portfolio-overview.md",
		title: "Get total portfolio value across all chains",
		content:
			'# Get total portfolio value across all chains\n\nFetches the aggregate USD value of all tokens held by a wallet address across every chain that DeBank tracks. This is the fastest way to get a single "net worth" number for any address without having to query each chain individually.\n\n```js\nasync function run(debank) {\n  const result = await debank.user.getUserTotalBalance({ id: "0xWALLET" });\n  // result.total_usd_value: total portfolio value in USD\n  // result.chain_list: per-chain breakdown\n  return result;\n}\n```\n',
	},
	{
		kind: "prose",
		id: "cookbook:02-chain-specific-balance.md",
		title: "Get balances for a wallet on one chain",
		content:
			'# Get balances for a wallet on one chain\n\nReturns token balances and total USD value for a wallet restricted to a single chain. Use this when you want chain-scoped data rather than the cross-chain aggregate from `getUserTotalBalance`.\n\n```js\nasync function run(debank) {\n  const result = await debank.user.getUserChainBalance({\n    id: "0xWALLET",\n    chain_id: "eth",\n  });\n  // result.usd_value: total balance on that chain in USD\n  return result;\n}\n```\n',
	},
	{
		kind: "prose",
		id: "cookbook:03-all-nft-holdings.md",
		title: "List all NFTs across chains",
		content:
			'# List all NFTs across chains\n\nReturns every NFT held by a wallet across all chains DeBank indexes. The response includes collection metadata, token IDs, and estimated USD values where available. This is the single call to use when you need a full picture of someone\'s NFT holdings.\n\n```js\nasync function run(debank) {\n  const nfts = await debank.user.getUserAllNftList({ id: "0xWALLET" });\n  // Each entry has: chain, contract_name, contract_id, inner_id, usd_price\n  return nfts.map((n) => ({\n    chain: n.chain,\n    collection: n.contract_name,\n    tokenId: n.inner_id,\n    usd: n.usd_price ?? 0,\n  }));\n}\n```\n',
	},
	{
		kind: "prose",
		id: "cookbook:04-token-approvals-audit.md",
		title: "Find risky token approvals",
		content:
			'# Find risky token approvals\n\nRetrieves all ERC-20 token approvals a wallet has granted across every chain it has interacted with. Use this to surface unlimited or unusually large approvals that could be revoked to reduce attack surface.\n\nNote: the v0.1 service signature accepts `{id}` only — there is no `chain_id` filter. The method internally queries approvals on every chain the wallet has activity on.\n\n```js\nasync function run(debank) {\n  const approvals = await debank.user.getUserTokenAuthorizedList({ id: "0xWALLET" });\n  // Filter to unlimited or very large approvals\n  const risky = approvals.filter(\n    (a) => a.value === "unlimited" || Number(a.value) > 1e20,\n  );\n  return risky.map((a) => ({\n    chain: a.chain,\n    token: a.symbol,\n    spender: a.spender_list?.[0]?.id,\n    value: a.value,\n  }));\n}\n```\n',
	},
	{
		kind: "prose",
		id: "cookbook:05-transaction-history.md",
		title: "Get last N transactions",
		content:
			'# Get last N transactions\n\nFetches the most recent transactions for a wallet on a specific chain. Useful for reconstructing activity history, finding a specific transfer, or auditing recent on-chain behaviour.\n\n```js\nasync function run(debank) {\n  const txs = await debank.user.getUserHistoryList({\n    id: "0xWALLET",\n    chain_id: "eth",\n    page_count: 20,\n  });\n  // Each entry has: time_at, tx (hash, from, to, value), sends, receives\n  return txs.map((t) => ({\n    hash: t.id,\n    time: new Date(t.time_at * 1000).toISOString(),\n    sends: t.sends,\n    receives: t.receives,\n  }));\n}\n```\n',
	},
	{
		kind: "prose",
		id: "cookbook:06-gas-and-simulate.md",
		title: "Check gas and simulate a transaction",
		content:
			'# Check gas and simulate a transaction\n\nFetches current gas price tiers for a chain and optionally pre-executes a transaction to estimate gas usage and detect potential reverts — all before committing anything on-chain.\n\n```js\nasync function run(debank) {\n  // Step 1: get current gas prices\n  const gas = await debank.chain.getGasPrices({ chain_id: "eth" });\n  // gas.slow / gas.normal / gas.fast: gwei tiers\n\n  // Step 2: pre-execute (simulate) a transaction\n  const simulation = await debank.transaction.preExecTransaction({\n    tx: JSON.stringify({\n      from: "0xWALLET",\n      to: "0xCONTRACT",\n      data: "0x",\n      value: "0x0",\n      gas: "0x5208",\n      gasPrice: String(gas.normal.price),\n    }),\n  });\n  // simulation.pre_exec: { success, error_message }\n  return { gas, simulation };\n}\n```\n',
	},
	{
		kind: "prose",
		id: "cookbook:07-protocol-positions.md",
		title: "List user positions in a specific DeFi protocol",
		content:
			'# List user positions in a specific DeFi protocol\n\nReturns a wallet\'s current positions inside a named DeFi protocol — LP shares, lending deposits, staking balances, etc. You need to know the DeBank `protocol_id` (e.g. `"uniswap"`, `"aave2"`, `"curve"`).\n\n```js\nasync function run(debank) {\n  const protocol = await debank.user.getUserProtocol({\n    id: "0xWALLET",\n    protocol_id: "uniswap",\n  });\n  // protocol.portfolio_item_list: array of position items with\n  //   detail_types, detail (tokens, reward tokens), stats.net_usd_value\n  return protocol.portfolio_item_list.map((p) => ({\n    name: p.name,\n    netUsd: p.stats.net_usd_value,\n    assetUsd: p.stats.asset_usd_value,\n  }));\n}\n```\n',
	},
	{
		kind: "prose",
		id: "cookbook:08-net-value-curve.md",
		title: "Get 24h net value curve",
		content:
			'# Get 24h net value curve\n\nReturns the net-worth time series for a wallet over the past 24 hours. The response is a flat array of `{ timestamp, usd_value }` data points — no unwrap step.\n\n```js\nasync function run(debank) {\n  const points = await debank.user.getUserTotalNetCurve({ id: "0xWALLET" });\n\n  // Each point: { timestamp: number, usd_value: number }\n  const last7 = points.slice(-7);\n  const latest = last7[last7.length - 1];\n  const earliest = last7[0];\n  const changePct =\n    earliest.usd_value > 0\n      ? ((latest.usd_value - earliest.usd_value) / earliest.usd_value) * 100\n      : 0;\n\n  return { last7, changePct: changePct.toFixed(2) };\n}\n```\n',
	},
	{
		kind: "prose",
		id: "cookbook:09-resolve-chain-names.md",
		title: "Convert user-facing chain names to DeBank chain IDs",
		content:
			'# Convert user-facing chain names to DeBank chain IDs\n\nUsers often refer to chains by common aliases ("BSC", "Binance", "Polygon", "Matic"). DeBank APIs expect lowercase short IDs like `"bsc"`, `"matic"`, `"eth"`. Use `debank.resolveChain()` to translate any human-readable name into the correct chain ID before passing it to other methods.\n\n```js\nasync function run(debank) {\n  // resolveChain handles common aliases — case-insensitive\n  const bscId = await debank.resolveChain("BSC");         // "bsc"\n  const ethId = await debank.resolveChain("Ethereum");    // "eth"\n  const maticId = await debank.resolveChain("Polygon");   // "matic"\n\n  // Now use the resolved IDs in subsequent calls\n  const balance = await debank.user.getUserChainBalance({\n    id: "0xWALLET",\n    chain_id: bscId,\n  });\n  return { bscId, ethId, maticId, balance };\n}\n```\n',
	},
	{
		kind: "prose",
		id: "cookbook:10-token-price-history.md",
		title: "Get historical price for a token",
		content:
			'# Get historical price for a token\n\nReturns the USD price of a specific token on a specific chain at a given historical date. Useful for computing cost-basis, PnL on historical holdings, or charting price movements.\n\n```js\nasync function run(debank) {\n  const priceData = await debank.token.getTokenHistoryPrice({\n    id: "0xdac17f958d2ee523a2206206994597c13d831ec7", // USDT on Ethereum\n    chain_id: "eth",\n    date_at: "2024-01-01",\n  });\n  // priceData.price: USD price at that date\n  return {\n    token: priceData.symbol,\n    date: "2024-01-01",\n    price: priceData.price,\n  };\n}\n```\n',
	},
];
