// scripts/build-docs-index.ts
//
// Runs at `pnpm build:docs` / `pnpm prebuild`. Walks the pure
// src/mcp/legacy/tool-metadata.ts module and produces a self-contained
// embedded index in src/mcp/search-docs/embedded-index.ts. Also slurps
// any *.md files under src/mcp/search-docs/cookbook/ as prose entries.
//
// IMPORTANT: this module imports tool-metadata.ts only; that module is
// side-effect-free. Importing it must NOT trigger services/index.ts.

import { execSync } from "node:child_process";
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";
import { TOOL_METADATA } from "../src/mcp/legacy/tool-metadata.js";

const repoRoot = path.resolve(
	path.dirname(fileURLToPath(import.meta.url)),
	"..",
);
const cookbookDir = path.join(repoRoot, "src/mcp/search-docs/cookbook");
const outFile = path.join(repoRoot, "src/mcp/search-docs/embedded-index.ts");

async function loadCookbook(): Promise<
	{ id: string; title: string; content: string }[]
> {
	const entries: { id: string; title: string; content: string }[] = [];
	try {
		const files = (await fs.readdir(cookbookDir))
			.filter((f) => f.endsWith(".md"))
			.sort();
		for (const f of files) {
			const md = await fs.readFile(path.join(cookbookDir, f), "utf-8");
			const firstHeader = md.split("\n").find((l) => l.startsWith("# "));
			const title = firstHeader ? firstHeader.replace(/^#\s+/, "") : f;
			entries.push({ id: `cookbook:${f}`, title, content: md });
		}
	} catch (err) {
		if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
	}
	return entries;
}

// Serialise a plain JS value to a TypeScript/Biome-compliant literal.
// Rules:
//   - Object keys that are valid JS identifiers → unquoted
//   - String values → JSON.stringify (keeps double quotes)
//   - Trailing comma on every property / array element
//   - Tab indentation (one extra tab per nesting level)
function serialize(value: unknown, depth = 0): string {
	const tab = "\t".repeat(depth);
	const tab1 = "\t".repeat(depth + 1);

	if (value === null) return "null";
	if (typeof value === "boolean") return String(value);
	if (typeof value === "number") return String(value);
	if (typeof value === "string") return JSON.stringify(value);

	if (Array.isArray(value)) {
		if (value.length === 0) return "[]";
		const items = value
			.map((v) => `${tab1}${serialize(v, depth + 1)}`)
			.join(",\n");
		return `[\n${items},\n${tab}]`;
	}

	if (typeof value === "object") {
		const obj = value as Record<string, unknown>;
		const keys = Object.keys(obj);
		if (keys.length === 0) return "{}";
		const IDENT = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/;
		const lines = keys.map((k) => {
			const key = IDENT.test(k) ? k : JSON.stringify(k);
			return `${tab1}${key}: ${serialize(obj[k], depth + 1)}`;
		});
		return `{\n${lines.join(",\n")},\n${tab}}`;
	}

	return JSON.stringify(value);
}

async function main() {
	const cookbook = await loadCookbook();
	const methodEntries = TOOL_METADATA.map((m) => ({
		kind: "method" as const,
		name: m.name,
		qualified: m.qualified,
		description: m.description,
		params: z.toJSONSchema(m.parameters),
		exampleCall: m.exampleCall,
	}));

	const entries = [
		...methodEntries,
		...cookbook.map((c) => ({ kind: "prose" as const, ...c })),
	];

	// Biome requires tabs and unquoted object keys. The custom serializer below
	// emits tab-indented output with unquoted keys; the final `biome format`
	// pass after writing (line 130) handles the remaining formatting rules
	// (string-literal length wrapping, etc.) that aren't worth replicating
	// in-script.
	const out = `// AUTO-GENERATED by scripts/build-docs-index.ts. Do not edit by hand.
// Re-run \`pnpm run build:docs\` to regenerate.

export type MethodEntry = {
\tkind: "method";
\tname: string;
\tqualified: string;
\tdescription: string;
\tparams: unknown;
\texampleCall: string;
};

export type ProseEntry = {
\tkind: "prose";
\tid: string;
\ttitle: string;
\tcontent: string;
};

export type IndexEntry = MethodEntry | ProseEntry;

export const ENTRIES: IndexEntry[] = ${serialize(entries)};
`;

	await fs.writeFile(outFile, out);
	// Auto-format with Biome so the committed file always passes `pnpm lint`.
	execSync(`pnpm exec biome format --write ${outFile}`, { stdio: "inherit" });
	console.log(`Wrote ${entries.length} entries to ${outFile}`);
}

void main();
