// AUTO-GENERATED by scripts/build-instructions.ts. Do not edit by hand.
// Re-run `pnpm run build:instructions` to regenerate.

export const INSTRUCTIONS = `# DeBank MCP — Code Mode Operational Guide

## ⚠ CRITICAL — read this first

For "what tokens does this wallet hold across all chains", call **\`debank.user.getUserTokensAcrossChains({ id, min_usd_value: 1 })\` in one execute**. That's it. The host fans out to every active chain in parallel and returns a flat token list — no manual orchestration, no \`Promise.all\`, no per-chain calls from the guest. See §4 for the canonical template and projection patterns.

---

This server exposes two primary tools to agents: \`execute\` (sandboxed JavaScript against a DeBank client) and \`search_docs\` (search SDK documentation). These two tools handle the full workflow — discovery, projection, multi-step composition — through agent-authored JavaScript in \`execute\`.

For agents that prefer explicit per-endpoint dispatch instead of authoring JS bodies, start the server with \`--tools=dynamic\` (or \`DEBANK_MCP_TOOLS=dynamic\`). That adds four tools: \`debank_resolve\`, \`list_endpoints\`, \`get_endpoint_schema\`, and \`invoke_endpoint\` (the last carrying an optional \`jq_filter\` for host-side projection).

## When to use which tool

- **\`execute\`** — the default and recommended path. Multi-step workflows, loops, joins, conditional logic, custom projection. The expressive default.
- **\`search_docs\`** — discovery. Find the right method by free-text query before authoring \`execute\` code.

## Top operations

### 1. Total portfolio value across all chains

\`\`\`js
async function run(debank) {
  return await debank.user.getUserTotalBalance({ id: "0xWALLET" });
}
\`\`\`

### 2. Balances on a specific chain

\`\`\`js
async function run(debank) {
  return await debank.user.getUserChainBalance({ id: "0xWALLET", chain_id: "eth" });
}
\`\`\`

### 3. NFTs across all chains

\`\`\`js
async function run(debank) {
  return await debank.user.getUserAllNftList({ id: "0xWALLET" });
}
\`\`\`

### 4. Token holdings across chains — canonical template

\`\`\`js
async function run(debank) {
  // One call. The host discovers active chains via getUserTotalBalance,
  // filters to those holding value, and fans out per-chain token_list
  // calls in parallel — all inside the service layer. The agent never
  // orchestrates the fan-out itself.
  const tokens = await debank.user.getUserTokensAcrossChains({
    id: "0xWALLET",
    min_usd_value: 1,   // skip the long tail of dust chains
  });

  // Project + sort on the host side. Each token already carries its \`chain\`.
  return tokens
    .map(t => ({
      symbol: t.symbol,
      chain: t.chain,
      usd: (t.amount ?? 0) * (t.price ?? 0),
    }))
    .filter(t => t.usd >= 1)
    .sort((a, b) => b.usd - a.usd);
}
\`\`\`

If the user asked about a **specific chain only**, call \`debank.user.getUserTokenList({ id, chain_id })\` directly with the known \`chain_id\` — no need to go through the cross-chain aggregate.

### 5. Find risky token approvals

\`\`\`js
async function run(debank) {
  // \`chain_id\` is required by DeBank's upstream for this endpoint. Each
  // returned entry is a token with a \`spenders[]\` array — one entry per
  // address authorised to spend that token. The \`value\` on a spender is
  // raw token units; unlimited approvals show up as ~1.16e77 (max uint256).
  const approvals = await debank.user.getUserTokenAuthorizedList({ id: "0xWALLET", chain_id: "eth" });
  return approvals.flatMap(t =>
    t.spenders
      .filter(s => s.value > 1e20)  // approximation of "unlimited"
      .map(s => ({ symbol: t.symbol, spender: s.id, protocol: s.protocol?.name ?? null, risk: s.risk_level }))
  );
}
\`\`\`

### 6. Recent transactions

\`\`\`js
async function run(debank) {
  return await debank.user.getUserHistoryList({ id: "0xWALLET", chain_id: "eth", page_count: 20 });
}
\`\`\`

### 7. Current gas on a chain

\`\`\`js
async function run(debank) {
  return await debank.chain.getGasPrices({ chain_id: "eth" });
}
\`\`\`

### 8. Simulate a transaction before sending

\`\`\`js
async function run(debank) {
  return await debank.transaction.preExecTransaction({
    tx: JSON.stringify({ from: "0xWALLET", to: "0xCONTRACT", data: "0x...", value: "0x0" }),
  });
}
\`\`\`

### 9. List user positions in a specific DeFi protocol

\`\`\`js
async function run(debank) {
  return await debank.user.getUserProtocol({ id: "0xWALLET", protocol_id: "uniswap" });
}
\`\`\`

### 10. Token price on a specific historical date

\`\`\`js
async function run(debank) {
  return await debank.token.getTokenHistoryPrice({
    id: "0xdac17f958d2ee523a2206206994597c13d831ec7",
    chain_id: "eth",
    date_at: "2024-01-01",
  });
}
\`\`\`

## Chain ID conventions

| User-facing name | DeBank chain_id |
|---|---|
| Ethereum, ETH | eth |
| Binance Smart Chain, BSC, BNB Chain | bsc |
| Polygon, Matic | matic |
| Arbitrum | arb |
| Optimism, OP | op |
| Base | base |
| Avalanche, AVAX | avax |

If unsure, call \`debank_resolve\` or \`await debank.resolveChain("...")\` inside \`execute()\`.

## Wrapped token keywords

The \`debank.resolveWrappedToken(keyword, chain_id)\` helper converts the keywords \`"WETH"\`, \`"wrapped native"\`, and \`"native token"\` to the chain's wrapped-token address. **You must call it explicitly** — passing one of those strings directly as a \`token_id\` or \`id\` argument inside a \`debank.*\` call will NOT auto-resolve. Example:

\`\`\`js
async function run(debank) {
  const wethAddr = debank.resolveWrappedToken("WETH", "eth");
  return await debank.token.getTokenInformation({ id: wethAddr, chain_id: "eth" });
}
\`\`\`

## Common patterns

### Pagination
The DeBank API uses offset-based pagination via \`start\` and \`limit\` (or \`page_count\` for history). Always paginate inside a single \`execute\` block — variables don't persist between calls.

### Error handling
**Throw** to indicate failure: uncaught exceptions from \`run(debank)\` are caught by the runtime and returned as \`{ok: false, error: <message>}\` with \`isError: true\` in the MCP envelope. **Returning** an error-shaped object (e.g. \`return { error: "..." }\`) is a *successful* result — the runtime wraps it as \`{ok: true, result: { error: "..." }}\` and the agent sees no failure signal. If something genuinely failed, \`throw\`. **The server does NOT retry upstream errors on your behalf.** If a \`debank.*\` call fails, decide whether to retry from your own code. For transient errors (network blip, DeBank 429, 5xx) a short \`for\`-loop with a small delay is fine; for hard 4xx errors retrying is pointless. Variables don't persist between \`execute\` calls, so put any retry loop inside one \`execute\` body.

Example pattern (uses the sandbox-provided \`sleep(ms)\` helper — \`setTimeout\` is NOT available in the sandbox; \`sleep\` is the only timer):

\`\`\`js
async function run(debank) {
  for (let i = 0; i < 3; i++) {
    try {
      return await debank.user.getUserTotalBalance({ id: "0xWALLET" });
    } catch (err) {
      if (i === 2) throw err;
      await sleep(500 * (i + 1));   // bounded by the 30 s outer deadline
    }
  }
}
\`\`\`

### Projection
Return only what you need. The result crosses the V8 boundary as a JSON copy — keep payloads small.

## Sandbox constraints

- JavaScript only — no TypeScript syntax (no \`: string\`, no generics).
- No \`process\`, no \`require\`, no \`import\`, no \`eval\`.
- No \`fetch\` outside the \`debank\` client.
- No \`setTimeout\` / \`setInterval\`. Use \`await sleep(ms)\` instead — the only timer the sandbox provides. Bounded by the 30 s outer deadline.
- 30 s outer wall-clock per \`execute\`.
- 5 s per \`debank.*\` call; on timeout you'll see \`"DeBank call timed out after 5s: <method>"\`.
- No persistent state between \`execute\` calls.

## --tools=dynamic mode (opt-in)

Start the server with \`--tools=dynamic\` or set \`DEBANK_MCP_TOOLS=dynamic\` to register four additional tools: \`debank_resolve\`, \`list_endpoints\`, \`get_endpoint_schema\`, and \`invoke_endpoint\`.

### \`invoke_endpoint\` quick reference

\`\`\`json
{
  "name": "debank.user.getUserChainBalance",
  "params": { "id": "0xWALLET", "chain_id": "eth" },
  "jq_filter": ".usd_value"
}
\`\`\`

The response is the jq-projected JSON. Use \`get_endpoint_schema\` first to see the full response shape.
`;
