// AUTO-GENERATED by scripts/build-instructions.ts. Do not edit by hand.
// Re-run `pnpm run build:instructions` to regenerate.

export const INSTRUCTIONS = `# DeBank MCP — Code Mode Operational Guide

## ⚠ CRITICAL — read this first

These rules are derived from real session telemetry. Ignoring them produces 5 s timeouts and 3-minute round trips for queries that should finish in ~15 s.

1. **NEVER call \`debank.user.getUserAllTokenList\`.** DeBank's upstream cannot serve this endpoint within the 5 s per-call timeout for any active wallet — every attempt cancels at exactly 5000 ms. Use the fan-out pattern in §4 instead. There is no scenario where the all-chains endpoint is the right choice; small wallets are also fast under the fan-out.
2. **One \`execute\` call, not many.** The execute scope grants concurrency=10 and budget=100. A query that needs 30 per-chain lookups should issue ONE \`execute\` with \`Promise.all\` across all 30 — not ten executes of three. Every additional \`execute\` invocation costs ~10-30 s of agent thinking time between batches. Wall time is dominated by inter-execute gaps, not API latency.
3. **Discover with \`getUserTotalBalance\` first, then fan out.** The \`chain_list\` field already tells you which chains hold value — no need to call \`getUsedChainList\` separately, no need to query every chain. Filter to \`chain.usd_value >= 1\` and fan out only to those.

The canonical "all token holdings across chains" template is §4 below. Copy it; don't reinvent it.

---

This server exposes two primary tools to agents: \`execute\` (sandboxed JavaScript against a DeBank client) and \`search_docs\` (search SDK documentation). These two tools handle the full workflow — discovery, projection, multi-step composition — through agent-authored JavaScript in \`execute\`.

For agents that prefer explicit per-endpoint dispatch instead of authoring JS bodies, start the server with \`--tools=dynamic\` (or \`DEBANK_MCP_TOOLS=dynamic\`). That adds four tools: \`debank_resolve\`, \`list_endpoints\`, \`get_endpoint_schema\`, and \`invoke_endpoint\` (the last carrying an optional \`jq_filter\` for host-side projection).

## When to use which tool

- **\`execute\`** — the default and recommended path. Multi-step workflows, loops, joins, conditional logic, custom projection. The expressive default.
- **\`search_docs\`** — discovery. Find the right method by free-text query before authoring \`execute\` code.

## Top operations

### 1. Total portfolio value across all chains

\`\`\`js
async function run(debank) {
  return await debank.user.getUserTotalBalance({ id: "0xWALLET" });
}
\`\`\`

### 2. Balances on a specific chain

\`\`\`js
async function run(debank) {
  return await debank.user.getUserChainBalance({ id: "0xWALLET", chain_id: "eth" });
}
\`\`\`

### 3. NFTs across all chains

\`\`\`js
async function run(debank) {
  return await debank.user.getUserAllNftList({ id: "0xWALLET" });
}
\`\`\`

### 4. Token holdings across chains — canonical template

This is the **only** correct way to answer "what tokens does this wallet hold". It works for a single chain, a few chains, or 80+ chains: portfolio breakdown identifies which chains hold value, then a single \`Promise.all\` fans out per-chain \`token_list\` calls. Do not split this across multiple \`execute\` invocations — concurrency=10 and budget=100 let one call handle dozens of chains.

\`\`\`js
async function run(debank) {
  // Step 1: portfolio breakdown tells us which chains hold meaningful value.
  // The \`chain_list\` field on the response is the input to step 2 — there
  // is no need to also call getUsedChainList.
  const portfolio = await debank.user.getUserTotalBalance({ id: "0xWALLET" });
  const targetChains = portfolio.chain_list
    .filter(c => c.usd_value >= 1)
    .map(c => c.id);

  // Step 2: ALL chains in ONE Promise.all — the scope handles concurrency.
  // For a whale with 80+ used chains, step 1 typically narrows to <20 active
  // chains, and those 20 calls complete in ~3-5 s wall time (concurrency=10).
  const lists = await Promise.all(
    targetChains.map(chain_id =>
      debank.user.getUserTokenList({ id: "0xWALLET", chain_id, is_all: true })
    )
  );

  // Step 3: flatten, project, and filter dust on the host side.
  return lists.flat()
    .map(t => ({
      symbol: t.symbol,
      chain: t.chain,
      usd: (t.amount ?? 0) * (t.price ?? 0),
    }))
    .filter(t => t.usd >= 1)
    .sort((a, b) => b.usd - a.usd);
}
\`\`\`

If the user asked about a **specific chain only**, skip step 1 and call \`getUserTokenList\` directly with the known \`chain_id\`. The fan-out template above is the right starting point for any question that says "all chains", "everywhere", "across networks", or doesn't name a chain.

### 5. Find risky token approvals

\`\`\`js
async function run(debank) {
  // Note: v0.1 service signature is \`{id}\` only — this method queries
  // approvals across all chains the wallet has interacted with.
  const approvals = await debank.user.getUserTokenAuthorizedList({ id: "0xWALLET" });
  // Filter to unlimited approvals
  return approvals.filter(a => a.value === "unlimited" || Number(a.value) > 1e20);
}
\`\`\`

### 6. Recent transactions

\`\`\`js
async function run(debank) {
  return await debank.user.getUserHistoryList({ id: "0xWALLET", chain_id: "eth", page_count: 20 });
}
\`\`\`

### 7. Current gas on a chain

\`\`\`js
async function run(debank) {
  return await debank.chain.getGasPrices({ chain_id: "eth" });
}
\`\`\`

### 8. Simulate a transaction before sending

\`\`\`js
async function run(debank) {
  return await debank.transaction.preExecTransaction({
    tx: JSON.stringify({ from: "0xWALLET", to: "0xCONTRACT", data: "0x...", value: "0x0" }),
  });
}
\`\`\`

### 9. List user positions in a specific DeFi protocol

\`\`\`js
async function run(debank) {
  return await debank.user.getUserProtocol({ id: "0xWALLET", protocol_id: "uniswap" });
}
\`\`\`

### 10. Token price on a specific historical date

\`\`\`js
async function run(debank) {
  return await debank.token.getTokenHistoryPrice({
    id: "0xdac17f958d2ee523a2206206994597c13d831ec7",
    chain_id: "eth",
    date_at: "2024-01-01",
  });
}
\`\`\`

## Chain ID conventions

| User-facing name | DeBank chain_id |
|---|---|
| Ethereum, ETH | eth |
| Binance Smart Chain, BSC, BNB Chain | bsc |
| Polygon, Matic | matic |
| Arbitrum | arb |
| Optimism, OP | op |
| Base | base |
| Avalanche, AVAX | avax |

If unsure, call \`debank_resolve\` or \`await debank.resolveChain("...")\` inside \`execute()\`.

## Wrapped token keywords

The \`debank.resolveWrappedToken(keyword, chain_id)\` helper converts the keywords \`"WETH"\`, \`"wrapped native"\`, and \`"native token"\` to the chain's wrapped-token address. **You must call it explicitly** — passing one of those strings directly as a \`token_id\` or \`id\` argument inside a \`debank.*\` call will NOT auto-resolve. Example:

\`\`\`js
async function run(debank) {
  const wethAddr = debank.resolveWrappedToken("WETH", "eth");
  return await debank.token.getTokenInformation({ id: wethAddr, chain_id: "eth" });
}
\`\`\`

## Common patterns

### Pagination
The DeBank API uses offset-based pagination via \`start\` and \`limit\` (or \`page_count\` for history). Always paginate inside a single \`execute\` block — variables don't persist between calls.

### Error handling
**Throw** to indicate failure: uncaught exceptions from \`run(debank)\` are caught by the runtime and returned as \`{ok: false, error: <message>}\` with \`isError: true\` in the MCP envelope. **Returning** an error-shaped object (e.g. \`return { error: "..." }\`) is a *successful* result — the runtime wraps it as \`{ok: true, result: { error: "..." }}\` and the agent sees no failure signal. If something genuinely failed, \`throw\`. **The server does NOT retry upstream errors on your behalf.** If a \`debank.*\` call fails, decide whether to retry from your own code. For transient errors (network blip, DeBank 429, 5xx) a short \`for\`-loop with a small delay is fine; for hard 4xx errors retrying is pointless. Variables don't persist between \`execute\` calls, so put any retry loop inside one \`execute\` body.

Example pattern (uses the sandbox-provided \`sleep(ms)\` helper — \`setTimeout\` is NOT available in the sandbox; \`sleep\` is the only timer):

\`\`\`js
async function run(debank) {
  for (let i = 0; i < 3; i++) {
    try {
      return await debank.user.getUserTotalBalance({ id: "0xWALLET" });
    } catch (err) {
      if (i === 2) throw err;
      await sleep(500 * (i + 1));   // bounded by the 30 s outer deadline
    }
  }
}
\`\`\`

### Projection
Return only what you need. The result crosses the V8 boundary as a JSON copy — keep payloads small.

## Sandbox constraints

- JavaScript only — no TypeScript syntax (no \`: string\`, no generics).
- No \`process\`, no \`require\`, no \`import\`, no \`eval\`.
- No \`fetch\` outside the \`debank\` client.
- No \`setTimeout\` / \`setInterval\`. Use \`await sleep(ms)\` instead — the only timer the sandbox provides. Bounded by the 30 s outer deadline.
- 30 s outer wall-clock per \`execute\`.
- 5 s per \`debank.*\` call; on timeout you'll see \`"DeBank call timed out after 5s: <method>"\`.
- No persistent state between \`execute\` calls.

## Wrapper-shape gotcha

\`debank.user.getUserTotalNetCurve\` returns \`{usd_value_list: [...]}\` — unwrap before mapping:

\`\`\`js
async function run(debank) {
  const curve = await debank.user.getUserTotalNetCurve({ id: "0xWALLET" });
  return curve.usd_value_list.slice(-7);   // last 7 data points
}
\`\`\`

## --tools=dynamic mode (opt-in)

Start the server with \`--tools=dynamic\` or set \`DEBANK_MCP_TOOLS=dynamic\` to register four additional tools: \`debank_resolve\`, \`list_endpoints\`, \`get_endpoint_schema\`, and \`invoke_endpoint\`.

### \`invoke_endpoint\` quick reference

\`\`\`json
{
  "name": "debank.user.getUserChainBalance",
  "params": { "id": "0xWALLET", "chain_id": "eth" },
  "jq_filter": ".usd_value"
}
\`\`\`

The response is the jq-projected JSON. Use \`get_endpoint_schema\` first to see the full response shape.
`;
